[CmdletBinding()]
param(
    [Parameter()]
    [string] $ProjectPath = '.',

    [Parameter()]
    [ValidateSet('core', 'desktop')]
    [string] $TargetPowerShellEdition = 'core'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'GitHubActions.Logging.ps1')

$script:RequirementsFileName = 'psreq.psd1'
$script:LockfileFileName = 'psreq.lock.psd1'
$script:FallbackBranchSlug = 'lockfile'

function Find-ProjectRoot {
    param(
        [Parameter(Mandatory)]
        [string] $Path
    )

    $cursor = $Path

    if (Test-Path -LiteralPath $cursor -PathType Leaf) {
        $cursor = Split-Path -Parent -Path $cursor
    }

    if (-not (Test-Path -LiteralPath $cursor -PathType Container)) {
        throw "Path not found or not a directory: $Path"
    }

    $cursor = (Resolve-Path -LiteralPath $cursor).Path

    while ($true) {
        $requirementsPath = Join-Path $cursor $script:RequirementsFileName
        if (Test-Path -LiteralPath $requirementsPath -PathType Leaf) {
            return $cursor
        }

        $parent = Split-Path -Parent -Path $cursor
        if ([string]::IsNullOrWhiteSpace($parent) -or ($parent -eq $cursor)) {
            break
        }

        $cursor = $parent
    }

    throw "Project root not found. Missing psreq.psd1 from: $Path"
}

function Read-DataFile {
    param(
        [Parameter(Mandatory)]
        [string] $Path,

        [switch] $AllowMissing
    )

    if (Test-Path -LiteralPath $Path -PathType Leaf) {
        return Import-PowerShellDataFile -Path (Resolve-Path -LiteralPath $Path).Path
    }
    if ($AllowMissing) {
        return @{}
    }
    throw "Data file was not found: $Path"
}

function Get-HashtableSignature {
    param(
        [AllowNull()]
        [object] $Value
    )

    if ($null -eq $Value) {
        return ''
    }

    if ($Value -is [System.Collections.IDictionary]) {
        $segments = foreach ($key in @($Value.Keys | Sort-Object)) {
            '{0}={1}' -f $key, (Get-HashtableSignature -Value $Value[$key])
        }

        return "{$($segments -join ';')}"
    }

    if ($Value -is [System.Collections.IEnumerable] -and $Value -isnot [string]) {
        $segments = foreach ($item in $Value) {
            Get-HashtableSignature -Value $item
        }

        return "[$($segments -join ',')]"
    }

    [string] $Value
}

function Test-DataFileChanged {
    param(
        [AllowNull()]
        [object] $Before,

        [AllowNull()]
        [object] $After
    )

    (Get-HashtableSignature -Value $Before) -cne (Get-HashtableSignature -Value $After)
}

function ConvertTo-BranchSlug {
    param(
        [Parameter(Mandatory)]
        [string[]] $Names
    )

    $slug = (($Names -join '-') -replace '[^A-Za-z0-9]+', '-').Trim('-').ToLowerInvariant()
    if ([string]::IsNullOrWhiteSpace($slug)) {
        return $script:FallbackBranchSlug
    }

    $slug
}

function Get-BumpMetadata {
    param(
        [Parameter(Mandatory)]
        [System.Collections.IDictionary] $RequirementsData,

        [Parameter(Mandatory)]
        [System.Collections.IDictionary] $LockfileBeforeData,

        [Parameter(Mandatory)]
        [System.Collections.IDictionary] $LockfileAfterData,

        [Parameter(Mandatory)]
        [bool] $LockfileChanged
    )

    $directNames = [string[]] @($RequirementsData.Keys | Sort-Object)
    $changedDirectNames = [string[]] @(
        foreach ($name in $directNames) {
            if ((Get-HashtableSignature -Value $LockfileBeforeData[$name]) -cne (Get-HashtableSignature -Value $LockfileAfterData[$name])) {
                $name
            }
        }
    )

    $changedNames = [string[]] @(
        if ($changedDirectNames.Count -gt 0) {
            $changedDirectNames
        }
        elseif ($LockfileChanged) {
            foreach ($name in @(($LockfileBeforeData.Keys + $LockfileAfterData.Keys) | Sort-Object -Unique)) {
                if ((Get-HashtableSignature -Value $LockfileBeforeData[$name]) -cne (Get-HashtableSignature -Value $LockfileAfterData[$name])) {
                    $name
                }
            }
        }
    )

    $branchSlugNames = [string[]] @(
        if ($changedNames.Count -gt 0) {
            $changedNames
        }
        else {
            $script:FallbackBranchSlug
        }
    )

    $branchName = "pslrm-bump/$(ConvertTo-BranchSlug -Names $branchSlugNames)"
    if ($changedNames.Count -eq 0) {
        return [pscustomobject]@{
            BranchName = $branchName
            CommitMessage = 'Bump lockfile dependencies'
            PullRequestTitle = 'Bump lockfile dependencies'
            PullRequestBody = 'Automated dependency bump generated by Update-PSLResource.'
        }
    }

    if ($changedNames.Count -eq 1) {
        $name = $changedNames[0]
        $version = [string] $LockfileAfterData[$name].Version
        $summary = if ([string]::IsNullOrWhiteSpace($version)) {
            "Bump $name"
        }
        else {
            "Bump $name to $version"
        }

        $body = if ([string]::IsNullOrWhiteSpace($version)) {
            "Automated dependency bump generated by Update-PSLResource. Updated $name."
        }
        else {
            "Automated dependency bump generated by Update-PSLResource. Updated $name to $version."
        }

        return [pscustomobject]@{
            BranchName = $branchName
            CommitMessage = $summary
            PullRequestTitle = $summary
            PullRequestBody = $body
        }
    }

    $firstName = $changedNames[0]
    $remainingCount = $changedNames.Count - 1
    $bodySegments = foreach ($name in $changedNames) {
        $version = [string] $LockfileAfterData[$name].Version
        if ([string]::IsNullOrWhiteSpace($version)) {
            $name
        }
        else {
            "$name $version"
        }
    }

    [pscustomobject]@{
        BranchName = $branchName
        CommitMessage = "Bump $firstName and $remainingCount more dependencies"
        PullRequestTitle = "Bump $firstName and $remainingCount more dependencies"
        PullRequestBody = "Automated dependency bump generated by Update-PSLResource. Updated dependencies: $($bodySegments -join ', ')."
    }
}

function Get-CurrentBranchName {
    param(
        [Parameter(Mandatory)]
        [string] $RepositoryRoot
    )

    $branchName = @(& git -C $RepositoryRoot branch --show-current 2>$null)
    $resolvedBranchName = $branchName | Select-Object -Last 1
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($resolvedBranchName)) {
        return ''
    }

    $resolvedBranchName
}

function Resolve-BaseBranch {
    param(
        [Parameter(Mandatory)]
        [string] $RepositoryRoot
    )

    $currentBranchName = Get-CurrentBranchName -RepositoryRoot $RepositoryRoot
    if (-not [string]::IsNullOrWhiteSpace($currentBranchName)) {
        return $currentBranchName
    }

    if (-not [string]::IsNullOrWhiteSpace($env:GITHUB_REF_NAME)) {
        return $env:GITHUB_REF_NAME
    }

    if (-not [string]::IsNullOrWhiteSpace($env:DEFAULT_BRANCH)) {
        return $env:DEFAULT_BRANCH
    }

    ''
}

function Set-ActionOutput {
    param(
        [Parameter(Mandatory)]
        [string] $Name,

        [Parameter(Mandatory)]
        [AllowNull()]
        [string] $Value
    )

    if ([string]::IsNullOrWhiteSpace($env:GITHUB_OUTPUT)) {
        Write-Host "Output $Name=$Value"
        return
    }

    "${Name}=${Value}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
}

$resolvedProjectPath = if ([System.IO.Path]::IsPathRooted($ProjectPath)) {
    [System.IO.Path]::GetFullPath($ProjectPath)
}
else {
    [System.IO.Path]::GetFullPath((Join-Path (Get-Location) $ProjectPath))
}
$projectRoot = $null
$lockfileChanged = $false
$repositoryRoot = $null
$lockfilePath = $null
$baseBranch = ''
$bumpMetadata = $null

Start-LogGroup -Title 'Bootstrap'
try {
    Write-Host "Project path: '${resolvedProjectPath}' Target PowerShell edition: '${TargetPowerShellEdition}'"

    $projectRoot = Find-ProjectRoot -Path $resolvedProjectPath
    Write-Host "Project root: '${projectRoot}'"

    if (-not (Get-Command -Name 'Update-PSLResource' -ErrorAction SilentlyContinue)) {
        throw 'Update-PSLResource is not available. Ensure the action bootstrap imported pslrm before invoking the script.'
    }

    Write-Host 'Project validation completed.'
}
finally {
    Stop-LogGroup
}

Start-LogGroup -Title 'Update lockfile'
try {
    $requirementsPath = Join-Path $projectRoot $script:RequirementsFileName
    $lockfilePath = Join-Path $projectRoot $script:LockfileFileName
    $requirementsData = Read-DataFile -Path $requirementsPath
    $lockfileBeforeData = Read-DataFile -Path $lockfilePath -AllowMissing

    Update-PSLResource -Path $projectRoot

    $lockfileAfterData = Read-DataFile -Path $lockfilePath
    $lockfileChanged = Test-DataFileChanged -Before $lockfileBeforeData -After $lockfileAfterData

    # NOTE: The action is only allowed to modify the lockfile. Scope git status to the
    # target project so unexpected changes in the same checkout fail the run immediately.
    $repositoryRootResult = @(& git -C $projectRoot rev-parse --show-toplevel 2>$null)
    $resolvedRepositoryRoot = $repositoryRootResult | Select-Object -Last 1
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($resolvedRepositoryRoot)) {
        throw 'Failed to resolve the git repository root. Ensure actions/checkout has run before invoking this action.'
    }

    $repositoryRoot = $resolvedRepositoryRoot
    $baseBranch = Resolve-BaseBranch -RepositoryRoot $repositoryRoot
    if ([string]::IsNullOrWhiteSpace($baseBranch)) {
        throw 'Failed to resolve the base branch for the bump pull request.'
    }

    $statusLines = @(& git -C $repositoryRoot status --porcelain --untracked-files=all -- $projectRoot 2>$null)
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to inspect git status under: $projectRoot"
    }

    $changedPaths = foreach ($line in $statusLines) {
        if ([string]::IsNullOrWhiteSpace($line)) {
            continue
        }

        $pathText = $line.Substring(3).Trim()
        if ($pathText.StartsWith('"') -and $pathText.EndsWith('"')) {
            $pathText = $pathText.Trim('"')
        }

        $pathText
    }

    $unexpectedPaths = [string[]] @($changedPaths | Where-Object { $_ -notmatch '(^|[\\/])psreq\.lock\.psd1$' })
    if ($unexpectedPaths.Count -gt 0) {
        throw "Unexpected changes detected outside psreq.lock.psd1: $($unexpectedPaths -join ', ')"
    }

    if ((-not $lockfileChanged) -and ($changedPaths | Where-Object { $_ -match '(^|[\\/])psreq\.lock\.psd1$' })) {
        Write-Warning 'The lockfile differs in git status, but the parsed lockfile data did not change. This usually indicates line-ending or formatting-only churn.'
    }

    $bumpMetadata = Get-BumpMetadata -RequirementsData $requirementsData -LockfileBeforeData $lockfileBeforeData -LockfileAfterData $lockfileAfterData -LockfileChanged $lockfileChanged

    Write-Host "Lockfile changed: $lockfileChanged"
}
finally {
    Stop-LogGroup
}

Start-LogGroup -Title 'Outputs'
try {
    $changedValue = if ($lockfileChanged) { 'true' } else { 'false' }

    Set-ActionOutput -Name 'changed' -Value $changedValue
    Set-ActionOutput -Name 'project_root' -Value $projectRoot
    Set-ActionOutput -Name 'repository_root' -Value $repositoryRoot
    Set-ActionOutput -Name 'lockfile_path' -Value $lockfilePath
    Set-ActionOutput -Name 'base_branch' -Value $baseBranch
    Set-ActionOutput -Name 'bump_branch_name' -Value $bumpMetadata.BranchName
    Set-ActionOutput -Name 'bump_commit_message' -Value $bumpMetadata.CommitMessage
    Set-ActionOutput -Name 'bump_pr_title' -Value $bumpMetadata.PullRequestTitle
    Set-ActionOutput -Name 'bump_pr_body' -Value $bumpMetadata.PullRequestBody
}
finally {
    Stop-LogGroup
}
