BeforeAll {
    $script:repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
    $script:scriptPath = Join-Path $script:repoRoot 'scripts/Invoke-BumpPullRequest.ps1'
}

Describe 'Invoke-BumpPullRequest' {
    BeforeEach {
        $script:originalBaseBranch = $env:BASE_BRANCH
        $script:originalBumpBranchName = $env:BUMP_BRANCH_NAME
        $script:originalGitHubToken = $env:GH_TOKEN
        $script:originalGithubOutput = $env:GITHUB_OUTPUT
        $script:originalPullRequestBody = $env:PR_BODY
        $script:originalPullRequestTitle = $env:PR_TITLE
        $script:originalRepositoryFullName = $env:REPOSITORY_FULL_NAME

        $env:BASE_BRANCH = 'main'
        $env:BUMP_BRANCH_NAME = 'pslrm-bump/pocof'
        $env:GH_TOKEN = 'token'
        $env:GITHUB_OUTPUT = Join-Path $TestDrive 'github-output.txt'
        $env:PR_BODY = 'Automated dependency bump generated by Update-PSLResource. Updated pocof to 0.23.0.'
        $env:PR_TITLE = 'Bump pocof to 0.23.0'
        $env:REPOSITORY_FULL_NAME = 'test-owner/test-repo'

        $global:GhCommands = [System.Collections.Generic.List[string[]]]::new()
        $global:CreatedPullRequestNumber = '12'
        $global:CreateCalled = $false
        $global:ExistingPullRequestBody = ''
        $global:ExistingPullRequestLabels = [string[]] @()
        $global:ExistingPullRequestNumber = ''
        $global:ExistingPullRequestTitle = ''
        $global:LabelCreateFailureNames = [string[]] @()
        $global:LabelCreateRaceNames = [string[]] @()
        $global:LabelListFails = $false
        $global:RepositoryLabelNames = [string[]] @()

        function global:gh {
            param(
                [Parameter(ValueFromRemainingArguments)]
                [object[]] $Arguments
            )

            $recordedArguments = [string[]] @(
                foreach ($argument in $Arguments) {
                    [string] $argument
                }
            )
            $global:GhCommands.Add($recordedArguments)
            $global:LASTEXITCODE = 0

            if (($Arguments[0] -eq 'label') -and ($Arguments[1] -eq 'list')) {
                if ($global:LabelListFails) {
                    $global:LASTEXITCODE = 1
                    'failed to query repository labels'
                    return
                }

                @(
                    foreach ($labelName in $global:RepositoryLabelNames) {
                        [pscustomobject]@{ name = $labelName }
                    }
                ) | ConvertTo-Json -Compress
                return
            }

            if (($Arguments[0] -eq 'label') -and ($Arguments[1] -eq 'create')) {
                $labelName = [string] $Arguments[2]
                if ($global:LabelCreateRaceNames -contains $labelName) {
                    $global:RepositoryLabelNames += $labelName
                    $global:LASTEXITCODE = 1
                    "label with name '$labelName' already exists"
                    return
                }

                if ($global:LabelCreateFailureNames -contains $labelName) {
                    $global:LASTEXITCODE = 1
                    "failed to create label '$labelName'"
                    return
                }

                if ($global:RepositoryLabelNames -notcontains $labelName) {
                    $global:RepositoryLabelNames += $labelName
                }
                return
            }

            if (($Arguments[0] -eq 'pr') -and ($Arguments[1] -eq 'list')) {
                if ($global:CreateCalled) {
                    $global:CreatedPullRequestNumber
                    return
                }

                if (-not [string]::IsNullOrWhiteSpace($global:ExistingPullRequestNumber)) {
                    $global:ExistingPullRequestNumber
                }

                return
            }

            if (($Arguments[0] -eq 'pr') -and ($Arguments[1] -eq 'view')) {
                [pscustomobject]@{
                    body = $global:ExistingPullRequestBody
                    labels = @(
                        foreach ($labelName in $global:ExistingPullRequestLabels) {
                            [pscustomobject]@{ name = $labelName }
                        }
                    )
                    title = $global:ExistingPullRequestTitle
                } | ConvertTo-Json -Compress
                return
            }

            if (($Arguments[0] -eq 'pr') -and ($Arguments[1] -eq 'create')) {
                $global:CreateCalled = $true
                return
            }

            if (($Arguments[0] -eq 'pr') -and ($Arguments[1] -eq 'edit')) {
                return
            }
        }

        function Get-RecordedGhCommand {
            @(
                foreach ($commandArguments in $global:GhCommands) {
                    $commandArguments -join ' '
                }
            )
        }

        function Get-RecordedGhCommandContaining {
            param(
                [Parameter(Mandatory)]
                [string] $Subcommand
            )

            @(
                foreach ($commandArguments in $global:GhCommands) {
                    if ($commandArguments -contains $Subcommand) {
                        $commandArguments -join ' '
                    }
                }
            )
        }
    }

    AfterEach {
        foreach ($environment in @(
                @{ Name = 'BASE_BRANCH'; Value = $script:originalBaseBranch },
                @{ Name = 'BUMP_BRANCH_NAME'; Value = $script:originalBumpBranchName },
                @{ Name = 'GH_TOKEN'; Value = $script:originalGitHubToken },
                @{ Name = 'GITHUB_OUTPUT'; Value = $script:originalGithubOutput },
                @{ Name = 'PR_BODY'; Value = $script:originalPullRequestBody },
                @{ Name = 'PR_TITLE'; Value = $script:originalPullRequestTitle },
                @{ Name = 'REPOSITORY_FULL_NAME'; Value = $script:originalRepositoryFullName }
            )) {
            if ($null -eq $environment.Value) {
                Remove-Item "Env:$($environment.Name)" -ErrorAction SilentlyContinue
            }
            else {
                Set-Item "Env:$($environment.Name)" -Value $environment.Value
            }
        }

        Remove-Item Function:\global:gh -ErrorAction SilentlyContinue
        foreach ($functionName in 'Get-RecordedGhCommand', 'Get-RecordedGhCommandContaining') {
            Remove-Item "Function:\$functionName" -ErrorAction SilentlyContinue
        }

        foreach ($variableName in 'GhCommands', 'CreatedPullRequestNumber', 'CreateCalled', 'ExistingPullRequestBody', 'ExistingPullRequestLabels', 'ExistingPullRequestNumber', 'ExistingPullRequestTitle', 'LabelCreateFailureNames', 'LabelCreateRaceNames', 'LabelListFails', 'RepositoryLabelNames') {
            Remove-Item "Variable:\global:$variableName" -ErrorAction SilentlyContinue
        }
    }

    It 'creates a new pull request when no open pull request exists' {
        & $script:scriptPath

        $commands = Get-RecordedGhCommand
        $outputLines = Get-Content -Path $env:GITHUB_OUTPUT

        @($commands | Where-Object { $_ -match '^pr create ' }).Count | Should -Be 1
        @($commands | Where-Object { $_ -match '^pr edit ' }).Count | Should -Be 0
        $commands | Should -Contain 'pr create --repo test-owner/test-repo --base main --head pslrm-bump/pocof --title Bump pocof to 0.23.0 --body Automated dependency bump generated by Update-PSLResource. Updated pocof to 0.23.0. --label dependencies --label pslrm'
        $outputLines | Should -Contain 'pull_request_action=created'
        $outputLines | Should -Contain 'pull_request_number=12'
    }

    It 'updates an existing pull request when title or body differ' {
        $global:ExistingPullRequestNumber = '7'
        $global:ExistingPullRequestTitle = 'Bump pocof'
        $global:ExistingPullRequestBody = 'Old body'
        $global:ExistingPullRequestLabels = @('dependencies', 'pslrm')

        & $script:scriptPath

        $commands = Get-RecordedGhCommand
        $viewCommands = @(Get-RecordedGhCommandContaining -Subcommand 'view')
        $outputLines = Get-Content -Path $env:GITHUB_OUTPUT

        $viewCommands.Count | Should -Be 1
        $viewCommands[0] | Should -Be (@('pr', 'view', $global:ExistingPullRequestNumber, '--repo', $env:REPOSITORY_FULL_NAME, '--json', 'title,body,labels') -join ' ')
        @($commands | Where-Object { $_ -match ' edit ' }).Count | Should -Be 1
        $outputLines | Should -Contain 'pull_request_action=updated'
        $outputLines | Should -Contain 'pull_request_number=7'
    }

    It 'does not update an existing pull request when title, body, and labels already match' {
        $global:ExistingPullRequestNumber = '7'
        $global:ExistingPullRequestTitle = 'Bump pocof to 0.23.0'
        $global:ExistingPullRequestBody = 'Automated dependency bump generated by Update-PSLResource. Updated pocof to 0.23.0.'
        $global:ExistingPullRequestLabels = @('dependencies', 'pslrm')

        & $script:scriptPath

        $commands = Get-RecordedGhCommand
        $viewCommands = @(Get-RecordedGhCommandContaining -Subcommand 'view')
        $outputLines = Get-Content -Path $env:GITHUB_OUTPUT

        $viewCommands.Count | Should -Be 1
        $viewCommands[0] | Should -Be (@('pr', 'view', $global:ExistingPullRequestNumber, '--repo', $env:REPOSITORY_FULL_NAME, '--json', 'title,body,labels') -join ' ')
        @($commands | Where-Object { $_ -match ' edit ' }).Count | Should -Be 0
        $outputLines | Should -Contain 'pull_request_action=noop'
        $outputLines | Should -Contain 'pull_request_number=7'
    }

    It 'creates missing repository labels without replacing existing labels' {
        $global:RepositoryLabelNames = @('Dependencies')

        & $script:scriptPath

        $commands = Get-RecordedGhCommand
        @($commands | Where-Object { $_ -eq 'label create dependencies --repo test-owner/test-repo --color 0366d6 --description Pull requests that update dependencies' }).Count | Should -Be 0
        @($commands | Where-Object { $_ -eq 'label create pslrm --repo test-owner/test-repo --color 012456 --description Pull requests created by pslrm-bump-action' }).Count | Should -Be 1
    }

    It 'adds only missing managed labels to an existing pull request' {
        $global:RepositoryLabelNames = @('dependencies', 'pslrm')
        $global:ExistingPullRequestNumber = '7'
        $global:ExistingPullRequestTitle = 'Bump pocof to 0.23.0'
        $global:ExistingPullRequestBody = 'Automated dependency bump generated by Update-PSLResource. Updated pocof to 0.23.0.'
        $global:ExistingPullRequestLabels = @('dependencies', 'custom')

        & $script:scriptPath

        $commands = Get-RecordedGhCommand
        $editCommands = @($commands | Where-Object { $_ -match '^pr edit ' })
        $outputLines = Get-Content -Path $env:GITHUB_OUTPUT

        $editCommands.Count | Should -Be 1
        $editCommands[0] | Should -Match '--add-label pslrm$'
        $editCommands[0] | Should -Not -Match '--add-label dependencies'
        $editCommands[0] | Should -Not -Match '--remove-label'
        $outputLines | Should -Contain 'pull_request_action=updated'
    }

    It 'continues when another process creates a missing repository label' {
        $global:LabelCreateRaceNames = @('dependencies')

        { & $script:scriptPath } | Should -Not -Throw

        @((Get-RecordedGhCommandContaining -Subcommand 'list') | Where-Object { $_ -match '^label list ' }).Count | Should -Be 2
        $global:RepositoryLabelNames | Should -Contain 'dependencies'
        $global:RepositoryLabelNames | Should -Contain 'pslrm'
    }

    It 'continues without a repository label that cannot be created' {
        $global:LabelCreateFailureNames = @('dependencies')

        { & $script:scriptPath } | Should -Not -Throw

        $createCommands = @(Get-RecordedGhCommandContaining -Subcommand 'create')
        $pullRequestCreateCommand = @($createCommands | Where-Object { $_ -match '^pr create ' })
        $pullRequestCreateCommand.Count | Should -Be 1
        $pullRequestCreateCommand[0] | Should -Not -Match '--label dependencies'
        $pullRequestCreateCommand[0] | Should -Match '--label pslrm$'
    }

    It 'creates an unlabeled pull request when no repository label can be created' {
        $global:LabelCreateFailureNames = @('dependencies', 'pslrm')

        { & $script:scriptPath } | Should -Not -Throw

        $createCommands = @(Get-RecordedGhCommandContaining -Subcommand 'create')
        $pullRequestCreateCommand = @($createCommands | Where-Object { $_ -match '^pr create ' })
        $pullRequestCreateCommand.Count | Should -Be 1
        $pullRequestCreateCommand[0] | Should -Not -Match '--label'
    }

    It 'creates an unlabeled pull request when repository labels cannot be queried' {
        $global:LabelListFails = $true

        { & $script:scriptPath } | Should -Not -Throw

        $commands = Get-RecordedGhCommand
        $pullRequestCreateCommand = @($commands | Where-Object { $_ -match '^pr create ' })
        $pullRequestCreateCommand.Count | Should -Be 1
        $pullRequestCreateCommand[0] | Should -Not -Match '--label'
        @($commands | Where-Object { $_ -match '^label create ' }).Count | Should -Be 0
    }

    It 'fails when GH_TOKEN is missing' {
        Remove-Item Env:GH_TOKEN -ErrorAction SilentlyContinue

        { & $script:scriptPath } | Should -Throw '*GH_TOKEN is required to authenticate GitHub CLI pull request operations.*'
    }
}
