BeforeAll {
    $script:repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
    $script:scriptPath = Join-Path $script:repoRoot 'scripts/Invoke-BumpPullRequest.ps1'
}

Describe 'Invoke-BumpPullRequest' {
    BeforeEach {
        $script:originalBaseBranch = $env:BASE_BRANCH
        $script:originalBumpBranchName = $env:BUMP_BRANCH_NAME
        $script:originalGitHubToken = $env:GH_TOKEN
        $script:originalGithubOutput = $env:GITHUB_OUTPUT
        $script:originalPullRequestBody = $env:PR_BODY
        $script:originalPullRequestTitle = $env:PR_TITLE
        $script:originalRepositoryFullName = $env:REPOSITORY_FULL_NAME

        $env:BASE_BRANCH = 'main'
        $env:BUMP_BRANCH_NAME = 'pslrm-bump/pocof'
        $env:GH_TOKEN = 'token'
        $env:GITHUB_OUTPUT = Join-Path $TestDrive 'github-output.txt'
        $env:PR_BODY = 'Automated dependency bump generated by Update-PSLResource. Updated pocof to 0.23.0.'
        $env:PR_TITLE = 'Bump pocof to 0.23.0'
        $env:REPOSITORY_FULL_NAME = 'test-owner/test-repo'

        $global:GhCommands = [System.Collections.Generic.List[string[]]]::new()
        $global:CreatedPullRequestNumber = '12'
        $global:CreateCalled = $false
        $global:ExistingPullRequestBody = ''
        $global:ExistingPullRequestNumber = ''
        $global:ExistingPullRequestTitle = ''

        function global:gh {
            param(
                [Parameter(ValueFromRemainingArguments)]
                [object[]] $Arguments
            )

            $recordedArguments = [string[]] @(
                foreach ($argument in $Arguments) {
                    [string] $argument
                }
            )
            $global:GhCommands.Add($recordedArguments)
            $global:LASTEXITCODE = 0

            if ($Arguments -contains 'list') {
                if ($global:CreateCalled) {
                    $global:CreatedPullRequestNumber
                    return
                }

                if (-not [string]::IsNullOrWhiteSpace($global:ExistingPullRequestNumber)) {
                    $global:ExistingPullRequestNumber
                }

                return
            }

            if ($Arguments -contains 'view') {
                [pscustomobject]@{
                    body = $global:ExistingPullRequestBody
                    title = $global:ExistingPullRequestTitle
                } | ConvertTo-Json -Compress
                return
            }

            if ($Arguments -contains 'create') {
                $global:CreateCalled = $true
                return
            }

            if ($Arguments -contains 'edit') {
                return
            }
        }

        function Get-RecordedGhCommands {
            @(
                foreach ($commandArguments in $global:GhCommands) {
                    $commandArguments -join ' '
                }
            )
        }

        function Get-RecordedGhCommandsContaining {
            param(
                [Parameter(Mandatory)]
                [string] $Subcommand
            )

            @(
                foreach ($commandArguments in $global:GhCommands) {
                    if ($commandArguments -contains $Subcommand) {
                        $commandArguments -join ' '
                    }
                }
            )
        }
    }

    AfterEach {
        foreach ($environment in @(
                @{ Name = 'BASE_BRANCH'; Value = $script:originalBaseBranch },
                @{ Name = 'BUMP_BRANCH_NAME'; Value = $script:originalBumpBranchName },
                @{ Name = 'GH_TOKEN'; Value = $script:originalGitHubToken },
                @{ Name = 'GITHUB_OUTPUT'; Value = $script:originalGithubOutput },
                @{ Name = 'PR_BODY'; Value = $script:originalPullRequestBody },
                @{ Name = 'PR_TITLE'; Value = $script:originalPullRequestTitle },
                @{ Name = 'REPOSITORY_FULL_NAME'; Value = $script:originalRepositoryFullName }
            )) {
            if ($null -eq $environment.Value) {
                Remove-Item "Env:$($environment.Name)" -ErrorAction SilentlyContinue
            }
            else {
                Set-Item "Env:$($environment.Name)" -Value $environment.Value
            }
        }

        foreach ($functionName in 'gh', 'Get-RecordedGhCommands', 'Get-RecordedGhCommandsContaining') {
            Remove-Item "Function:\global:$functionName" -ErrorAction SilentlyContinue
        }

        foreach ($variableName in 'GhCommands', 'CreatedPullRequestNumber', 'CreateCalled', 'ExistingPullRequestBody', 'ExistingPullRequestNumber', 'ExistingPullRequestTitle') {
            Remove-Item "Variable:\global:$variableName" -ErrorAction SilentlyContinue
        }
    }

    It 'creates a new pull request when no open pull request exists' {
        & $script:scriptPath

        $commands = Get-RecordedGhCommands
        $outputLines = Get-Content -Path $env:GITHUB_OUTPUT

        @($commands | Where-Object { $_ -match ' create ' }).Count | Should -Be 1
        @($commands | Where-Object { $_ -match ' edit ' }).Count | Should -Be 0
        $outputLines | Should -Contain 'pull_request_action=created'
        $outputLines | Should -Contain 'pull_request_number=12'
    }

    It 'updates an existing pull request when title or body differ' {
        $global:ExistingPullRequestNumber = '7'
        $global:ExistingPullRequestTitle = 'Bump pocof'
        $global:ExistingPullRequestBody = 'Old body'

        & $script:scriptPath

        $commands = Get-RecordedGhCommands
        $viewCommands = @(Get-RecordedGhCommandsContaining -Subcommand 'view')
        $outputLines = Get-Content -Path $env:GITHUB_OUTPUT

        $viewCommands.Count | Should -Be 1
        $viewCommands[0] | Should -Be (@('pr', 'view', $global:ExistingPullRequestNumber, '--repo', $env:REPOSITORY_FULL_NAME, '--json', 'title,body') -join ' ')
        @($commands | Where-Object { $_ -match ' edit ' }).Count | Should -Be 1
        $outputLines | Should -Contain 'pull_request_action=updated'
        $outputLines | Should -Contain 'pull_request_number=7'
    }

    It 'does not update an existing pull request when title and body already match' {
        $global:ExistingPullRequestNumber = '7'
        $global:ExistingPullRequestTitle = 'Bump pocof to 0.23.0'
        $global:ExistingPullRequestBody = 'Automated dependency bump generated by Update-PSLResource. Updated pocof to 0.23.0.'

        & $script:scriptPath

        $commands = Get-RecordedGhCommands
        $viewCommands = @(Get-RecordedGhCommandsContaining -Subcommand 'view')
        $outputLines = Get-Content -Path $env:GITHUB_OUTPUT

        $viewCommands.Count | Should -Be 1
        $viewCommands[0] | Should -Be (@('pr', 'view', $global:ExistingPullRequestNumber, '--repo', $env:REPOSITORY_FULL_NAME, '--json', 'title,body') -join ' ')
        @($commands | Where-Object { $_ -match ' edit ' }).Count | Should -Be 0
        $outputLines | Should -Contain 'pull_request_action=noop'
        $outputLines | Should -Contain 'pull_request_number=7'
    }

    It 'fails when GH_TOKEN is missing' {
        Remove-Item Env:GH_TOKEN -ErrorAction SilentlyContinue

        { & $script:scriptPath } | Should -Throw '*GH_TOKEN is required to authenticate GitHub CLI pull request operations.*'
    }
}